// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CloudTemplateDtoMachineSizeGroup.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CloudTemplateDtoMachineSizeGroup
    {
        [EnumMember(Value = "Small")]
        Small,
        [EnumMember(Value = "Medium")]
        Medium,
        [EnumMember(Value = "Large")]
        Large
    }
    internal static class CloudTemplateDtoMachineSizeGroupEnumExtension
    {
        internal static string ToSerializedValue(this CloudTemplateDtoMachineSizeGroup? value)
        {
            return value == null ? null : ((CloudTemplateDtoMachineSizeGroup)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CloudTemplateDtoMachineSizeGroup value)
        {
            switch( value )
            {
                case CloudTemplateDtoMachineSizeGroup.Small:
                    return "Small";
                case CloudTemplateDtoMachineSizeGroup.Medium:
                    return "Medium";
                case CloudTemplateDtoMachineSizeGroup.Large:
                    return "Large";
            }
            return null;
        }

        internal static CloudTemplateDtoMachineSizeGroup? ParseCloudTemplateDtoMachineSizeGroup(this string value)
        {
            switch( value )
            {
                case "Small":
                    return CloudTemplateDtoMachineSizeGroup.Small;
                case "Medium":
                    return CloudTemplateDtoMachineSizeGroup.Medium;
                case "Large":
                    return CloudTemplateDtoMachineSizeGroup.Large;
            }
            return null;
        }
    }
}
