// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ExtendedMachineDto : MachineDto
    {
        /// <summary>
        /// Initializes a new instance of the ExtendedMachineDto class.
        /// </summary>
        public ExtendedMachineDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExtendedMachineDto class.
        /// </summary>
        /// <param name="name">The name of the Machine a Robot is hosted
        /// on.</param>
        /// <param name="licenseKey">The key is automatically generated from
        /// the server for the Robot machine.
        /// &lt;para /&gt;For the robot to work, the same key must exist on
        /// both the robot and Orchestrator.
        /// &lt;para /&gt;All robots on a machine must have the same license
        /// key in order to register correctly.</param>
        /// <param name="type">The type of the Machine (Standard / Template).
        /// Possible values include: 'Standard', 'Template'</param>
        /// <param name="scope">The scope of the Machine (Default / Shared / PW
        /// / Cloud). Possible values include: 'Default', 'Shared',
        /// 'PersonalWorkspace', 'Cloud'</param>
        /// <param name="nonProductionSlots">Number of NonProduction slots to
        /// be reserved at runtime</param>
        /// <param name="unattendedSlots">Number of Unattended slots to be
        /// reserved at runtime</param>
        /// <param name="headlessSlots">Number of Headless slots to be reserved
        /// at runtime</param>
        /// <param name="testAutomationSlots">Number of TestAutomation slots to
        /// be reserved at runtime</param>
        /// <param name="key">An immutable unique identifier that is preserved
        /// during tenant migration</param>
        /// <param name="robotVersions">The versions of the Robots hosted on
        /// the Machine.</param>
        /// <param name="robotUsers">Robots assigned to template
        /// machine.</param>
        public ExtendedMachineDto(string name, string licenseKey = default(string), string description = default(string), MachineDtoType? type = default(MachineDtoType?), MachineDtoScope? scope = default(MachineDtoScope?), int? nonProductionSlots = default(int?), int? unattendedSlots = default(int?), int? headlessSlots = default(int?), int? testAutomationSlots = default(int?), System.Guid? key = default(System.Guid?), IList<MachinesRobotVersionDto> robotVersions = default(IList<MachinesRobotVersionDto>), IList<RobotUserDto> robotUsers = default(IList<RobotUserDto>), long? id = default(long?))
            : base(name, licenseKey, description, type, scope, nonProductionSlots, unattendedSlots, headlessSlots, testAutomationSlots, key, robotVersions, robotUsers, id)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
