// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for JobDtoProcessType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobDtoProcessType
    {
        [EnumMember(Value = "Process")]
        Process,
        [EnumMember(Value = "TestAutomationProcess")]
        TestAutomationProcess
    }
    internal static class JobDtoProcessTypeEnumExtension
    {
        internal static string ToSerializedValue(this JobDtoProcessType? value)
        {
            return value == null ? null : ((JobDtoProcessType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this JobDtoProcessType value)
        {
            switch( value )
            {
                case JobDtoProcessType.Process:
                    return "Process";
                case JobDtoProcessType.TestAutomationProcess:
                    return "TestAutomationProcess";
            }
            return null;
        }

        internal static JobDtoProcessType? ParseJobDtoProcessType(this string value)
        {
            switch( value )
            {
                case "Process":
                    return JobDtoProcessType.Process;
                case "TestAutomationProcess":
                    return JobDtoProcessType.TestAutomationProcess;
            }
            return null;
        }
    }
}
