// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MachineSessionRuntimeDtoStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MachineSessionRuntimeDtoStatus
    {
        [EnumMember(Value = "Available")]
        Available,
        [EnumMember(Value = "Busy")]
        Busy,
        [EnumMember(Value = "Disconnected")]
        Disconnected,
        [EnumMember(Value = "Unknown")]
        Unknown
    }
    internal static class MachineSessionRuntimeDtoStatusEnumExtension
    {
        internal static string ToSerializedValue(this MachineSessionRuntimeDtoStatus? value)
        {
            return value == null ? null : ((MachineSessionRuntimeDtoStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MachineSessionRuntimeDtoStatus value)
        {
            switch( value )
            {
                case MachineSessionRuntimeDtoStatus.Available:
                    return "Available";
                case MachineSessionRuntimeDtoStatus.Busy:
                    return "Busy";
                case MachineSessionRuntimeDtoStatus.Disconnected:
                    return "Disconnected";
                case MachineSessionRuntimeDtoStatus.Unknown:
                    return "Unknown";
            }
            return null;
        }

        internal static MachineSessionRuntimeDtoStatus? ParseMachineSessionRuntimeDtoStatus(this string value)
        {
            switch( value )
            {
                case "Available":
                    return MachineSessionRuntimeDtoStatus.Available;
                case "Busy":
                    return MachineSessionRuntimeDtoStatus.Busy;
                case "Disconnected":
                    return MachineSessionRuntimeDtoStatus.Disconnected;
                case "Unknown":
                    return MachineSessionRuntimeDtoStatus.Unknown;
            }
            return null;
        }
    }
}
