// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MachineSessionRuntimeDtoMachineType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MachineSessionRuntimeDtoMachineType
    {
        [EnumMember(Value = "Standard")]
        Standard,
        [EnumMember(Value = "Template")]
        Template
    }
    internal static class MachineSessionRuntimeDtoMachineTypeEnumExtension
    {
        internal static string ToSerializedValue(this MachineSessionRuntimeDtoMachineType? value)
        {
            return value == null ? null : ((MachineSessionRuntimeDtoMachineType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MachineSessionRuntimeDtoMachineType value)
        {
            switch( value )
            {
                case MachineSessionRuntimeDtoMachineType.Standard:
                    return "Standard";
                case MachineSessionRuntimeDtoMachineType.Template:
                    return "Template";
            }
            return null;
        }

        internal static MachineSessionRuntimeDtoMachineType? ParseMachineSessionRuntimeDtoMachineType(this string value)
        {
            switch( value )
            {
                case "Standard":
                    return MachineSessionRuntimeDtoMachineType.Standard;
                case "Template":
                    return MachineSessionRuntimeDtoMachineType.Template;
            }
            return null;
        }
    }
}
