// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MachineSessionRuntimeDtoMachineScope.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MachineSessionRuntimeDtoMachineScope
    {
        [EnumMember(Value = "Default")]
        Default,
        [EnumMember(Value = "Shared")]
        Shared,
        [EnumMember(Value = "PersonalWorkspace")]
        PersonalWorkspace,
        [EnumMember(Value = "Cloud")]
        Cloud
    }
    internal static class MachineSessionRuntimeDtoMachineScopeEnumExtension
    {
        internal static string ToSerializedValue(this MachineSessionRuntimeDtoMachineScope? value)
        {
            return value == null ? null : ((MachineSessionRuntimeDtoMachineScope)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MachineSessionRuntimeDtoMachineScope value)
        {
            switch( value )
            {
                case MachineSessionRuntimeDtoMachineScope.Default:
                    return "Default";
                case MachineSessionRuntimeDtoMachineScope.Shared:
                    return "Shared";
                case MachineSessionRuntimeDtoMachineScope.PersonalWorkspace:
                    return "PersonalWorkspace";
                case MachineSessionRuntimeDtoMachineScope.Cloud:
                    return "Cloud";
            }
            return null;
        }

        internal static MachineSessionRuntimeDtoMachineScope? ParseMachineSessionRuntimeDtoMachineScope(this string value)
        {
            switch( value )
            {
                case "Default":
                    return MachineSessionRuntimeDtoMachineScope.Default;
                case "Shared":
                    return MachineSessionRuntimeDtoMachineScope.Shared;
                case "PersonalWorkspace":
                    return MachineSessionRuntimeDtoMachineScope.PersonalWorkspace;
                case "Cloud":
                    return MachineSessionRuntimeDtoMachineScope.Cloud;
            }
            return null;
        }
    }
}
