// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MachineSessionRuntimeDtoRuntimeType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MachineSessionRuntimeDtoRuntimeType
    {
        [EnumMember(Value = "NonProduction")]
        NonProduction,
        [EnumMember(Value = "Attended")]
        Attended,
        [EnumMember(Value = "Unattended")]
        Unattended,
        [EnumMember(Value = "Studio")]
        Studio,
        [EnumMember(Value = "Development")]
        Development,
        [EnumMember(Value = "StudioX")]
        StudioX,
        [EnumMember(Value = "Headless")]
        Headless,
        [EnumMember(Value = "StudioPro")]
        StudioPro,
        [EnumMember(Value = "TestAutomation")]
        TestAutomation
    }
    internal static class MachineSessionRuntimeDtoRuntimeTypeEnumExtension
    {
        internal static string ToSerializedValue(this MachineSessionRuntimeDtoRuntimeType? value)
        {
            return value == null ? null : ((MachineSessionRuntimeDtoRuntimeType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MachineSessionRuntimeDtoRuntimeType value)
        {
            switch( value )
            {
                case MachineSessionRuntimeDtoRuntimeType.NonProduction:
                    return "NonProduction";
                case MachineSessionRuntimeDtoRuntimeType.Attended:
                    return "Attended";
                case MachineSessionRuntimeDtoRuntimeType.Unattended:
                    return "Unattended";
                case MachineSessionRuntimeDtoRuntimeType.Studio:
                    return "Studio";
                case MachineSessionRuntimeDtoRuntimeType.Development:
                    return "Development";
                case MachineSessionRuntimeDtoRuntimeType.StudioX:
                    return "StudioX";
                case MachineSessionRuntimeDtoRuntimeType.Headless:
                    return "Headless";
                case MachineSessionRuntimeDtoRuntimeType.StudioPro:
                    return "StudioPro";
                case MachineSessionRuntimeDtoRuntimeType.TestAutomation:
                    return "TestAutomation";
            }
            return null;
        }

        internal static MachineSessionRuntimeDtoRuntimeType? ParseMachineSessionRuntimeDtoRuntimeType(this string value)
        {
            switch( value )
            {
                case "NonProduction":
                    return MachineSessionRuntimeDtoRuntimeType.NonProduction;
                case "Attended":
                    return MachineSessionRuntimeDtoRuntimeType.Attended;
                case "Unattended":
                    return MachineSessionRuntimeDtoRuntimeType.Unattended;
                case "Studio":
                    return MachineSessionRuntimeDtoRuntimeType.Studio;
                case "Development":
                    return MachineSessionRuntimeDtoRuntimeType.Development;
                case "StudioX":
                    return MachineSessionRuntimeDtoRuntimeType.StudioX;
                case "Headless":
                    return MachineSessionRuntimeDtoRuntimeType.Headless;
                case "StudioPro":
                    return MachineSessionRuntimeDtoRuntimeType.StudioPro;
                case "TestAutomation":
                    return MachineSessionRuntimeDtoRuntimeType.TestAutomation;
            }
            return null;
        }
    }
}
