// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RobotUserDto
    {
        /// <summary>
        /// Initializes a new instance of the RobotUserDto class.
        /// </summary>
        public RobotUserDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RobotUserDto class.
        /// </summary>
        /// <param name="robotId">The Id of the Robot.</param>
        /// <param name="userName">The name of the user.</param>
        public RobotUserDto(long robotId, string userName = default(string))
        {
            UserName = userName;
            RobotId = robotId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of the user.
        /// </summary>
        [JsonProperty(PropertyName = "UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets the Id of the Robot.
        /// </summary>
        [JsonProperty(PropertyName = "RobotId")]
        public long RobotId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
