// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Optimus.LibOrquestrator.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TaskDataDtoWaitJobState.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TaskDataDtoWaitJobState
    {
        [EnumMember(Value = "Pending")]
        Pending,
        [EnumMember(Value = "Running")]
        Running,
        [EnumMember(Value = "Stopping")]
        Stopping,
        [EnumMember(Value = "Terminating")]
        Terminating,
        [EnumMember(Value = "Faulted")]
        Faulted,
        [EnumMember(Value = "Successful")]
        Successful,
        [EnumMember(Value = "Stopped")]
        Stopped,
        [EnumMember(Value = "Suspended")]
        Suspended,
        [EnumMember(Value = "Resumed")]
        Resumed
    }
    internal static class TaskDataDtoWaitJobStateEnumExtension
    {
        internal static string ToSerializedValue(this TaskDataDtoWaitJobState? value)
        {
            return value == null ? null : ((TaskDataDtoWaitJobState)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this TaskDataDtoWaitJobState value)
        {
            switch( value )
            {
                case TaskDataDtoWaitJobState.Pending:
                    return "Pending";
                case TaskDataDtoWaitJobState.Running:
                    return "Running";
                case TaskDataDtoWaitJobState.Stopping:
                    return "Stopping";
                case TaskDataDtoWaitJobState.Terminating:
                    return "Terminating";
                case TaskDataDtoWaitJobState.Faulted:
                    return "Faulted";
                case TaskDataDtoWaitJobState.Successful:
                    return "Successful";
                case TaskDataDtoWaitJobState.Stopped:
                    return "Stopped";
                case TaskDataDtoWaitJobState.Suspended:
                    return "Suspended";
                case TaskDataDtoWaitJobState.Resumed:
                    return "Resumed";
            }
            return null;
        }

        internal static TaskDataDtoWaitJobState? ParseTaskDataDtoWaitJobState(this string value)
        {
            switch( value )
            {
                case "Pending":
                    return TaskDataDtoWaitJobState.Pending;
                case "Running":
                    return TaskDataDtoWaitJobState.Running;
                case "Stopping":
                    return TaskDataDtoWaitJobState.Stopping;
                case "Terminating":
                    return TaskDataDtoWaitJobState.Terminating;
                case "Faulted":
                    return TaskDataDtoWaitJobState.Faulted;
                case "Successful":
                    return TaskDataDtoWaitJobState.Successful;
                case "Stopped":
                    return TaskDataDtoWaitJobState.Stopped;
                case "Suspended":
                    return TaskDataDtoWaitJobState.Suspended;
                case "Resumed":
                    return TaskDataDtoWaitJobState.Resumed;
            }
            return null;
        }
    }
}
